[package]
name = "copy_file"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[profile.release]
strip = true 
opt-level = "s"
lto = true
codegen-units = 1


[profile.dev]